services:
  web-pozos:
    image: php:apache
	depend_on:
	  - api-pozos
	ports:
	  - "8082:80"
	volumes:
	  - ./website:/var/www/html
	environment:
	  - USERNAME=toto
	  - PASSWORD=python
	networks:
	  -pozos-networks
	  
  api-pozos:
    image: api_pozos_image:1
	ports:
	  - "4000:5000"
	volumes:
	  - ./simple_api/student_age.json:data/student_age.json
	networks:
	  - pozos-networks
	  
networks:
  pozos-networks:
